from flask import Flask,jsonify; app=Flask(__name__)
@app.route("/health")
def h(): return jsonify({"status":"ok"})
@app.route("/ocr",methods=["POST"])
def ocr(): return jsonify({"text":"mock","confidence":0.99})
app.run(host="0.0.0.0",port=5001)